### ISSUE TITLE
HttpService missing `HttpEnabled` type

### ISSUE THREAD

**Issue by fisherjacobc** [roblox-ts/types#1189]
I noticed while working on a project that the [`HttpEnabled`](https://create.roblox.com/docs/reference/engine/classes/HttpService#HttpEnabled) property is missing from `HttpService`

**Comment by Dionysusnu** [comment]
Is this actually wrong? I'm trying to read `HttpEnabled` in studio, both in game testing and with a plugin, but both are erroring saying they need LocalUser permissions. What makes you believe this should be added to @rbxts/types?

**Comment by fisherjacobc** [comment]
Oh? Maybe you're right, I know you can set it in the command bar (which i presumed had the same access capabilities of plugins), but I thought you could read it in a regular script to check if it was enabled. So that seems like an oversight on my end (for not realizing you can't even read it), and also on roblox's end (for not letting us read it). I guess I would have to just make an http request inside a pcall/try-catch and use that to determine if `HttpService` is enabled.

**Comment by Dionysusnu** [comment]
> Oh? Maybe you're right, I know you can set it in the command bar (which i presumed had the same access capabilities of plugins)
The command bar has a slightly higher permission. In the API dump, it's `LocalUserSecurity`, whereas plugins have `PluginSecurity`.

> I guess I would have to just make an http request inside a pcall/try-catch and use that to determine if `HttpService` is enabled.
Yeah, pretty much.

**Comment by Dionysusnu** [comment]
_They're listening_
HttpEnabled just got changed to be `None` security for reading. https://github.com/MaximumADHD/Roblox-Client-Tracker/commit/dfff1f80fac9a8d41891ac231415ed3cf4bb7bd5#diff-099be3b8c79c155bf018fa90fb579a95e4d5f6a19476caf5b195834ecf1497d4R45158

Since the API dump reflects this correctly, an override in the generator is not necessary, so the linked PR can still be closed.

**Comment by fisherjacobc** [comment]
_they're in my walls, they're in my walls help_
good to know! will do
