### ISSUE TITLE
UDim2.fromOffset, UDim2.fromScale

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/types#153]
Two new static constructors were added for UDim2 but they're not enabled yet.

This issue is a reminder to add them.

```TS
interface UDim2Constructor {
	fromOffset(x: number, y: number): UDim2;
	fromScale(x: number, y: number): UDim2;
}
```

**Comment by Vorlias** [comment]
Both constructors work on production now, I believe. :)
