### ISSUE TITLE
`Title` is not a `readonly` property.

### ISSUE THREAD

**Issue by ClockworkSquirrel** [roblox-ts/types#211]
https://github.com/roblox-ts/types/blob/378d16f654d441024d62b2889419eb9ab4759d8d/include/generated/PluginSecurity.d.ts#L447

`Title` is currently a `readonly` property; however, `Title` is writable by plugins, and sets the text displayed at the top of a `DockWidgetPluginGui`.

**Comment by Validark** [comment]
Fixed by https://github.com/roblox-ts/types/commit/d03a5654022572a168ad0120918beaae33ed555b
