### ISSUE TITLE
DataStorePages is not compatible with the roblox-ts compiler

### ISSUE THREAD

**Issue by TheNickmaster21** [roblox-ts/types#217]
```
const result = game.GetService('DataStoreService').GetOrderedDataStore('test').GetSortedAsync(true, 0);
print(result.GetCurrentPage()[0].value);
```
causes the following compile time error:

`  - Compiler Error: result.GetCurrentPage()[0].value in print(result.GetCurrentPage()[0].value) is of type any which is not supported! Use type unknown instead.`

The type of the 'value' member of the Pages generic for DataStorePages should be unknown instead of any.

**Comment by Validark** [comment]
Fixed by https://github.com/roblox-ts/types/commit/a0321a31ad173f6ce1a0d4546d80c88e30ae0dad
