### ISSUE TITLE
AgentParameters type is missing "AgentCanJump"

### ISSUE THREAD

**Issue by Mr1Vgy** [roblox-ts/types#252]
According to the Roblox Developer Hub, there should be one more parameter, `AgentCanJump?: boolean` for the `AgentParameters` type used in the method 'CreatePath' (https://developer.roblox.com/en-us/api-reference/function/PathfindingService/CreatePath)

The AgentParameters interface in `roblox.d.ts` should be the following:
```
interface AgentParameters {
	/** Humanoid radius. Used to determine the minimum separation from obstacles. */
	AgentRadius?: number;
	/** Humanoid height.
	 * Empty space smaller than this value, like the space under stairs, will be marked as non-traversable.
	 */
	AgentHeight?: number;
	/** Sets whether off-mesh links for jumping are allowed. */
	AgentCanJump?: boolean;
}
```

**Comment by osyrisrblx** [comment]
Fixed in 1.0.350
