### ISSUE TITLE
Instance interface has 'unknown' as type for 'Changed'

### ISSUE THREAD

**Issue by cassis163** [roblox-ts/types#499]
This can be found in '\types\include\generated\None.d.ts':
```ts
readonly Changed: unknown;
```
My workaround looks like this at the moment:
```ts
(this._currentCamera.Changed as RBXScriptSignal<(property: string) => void>)
```

**Comment by OverHash** [comment]
This is intended behaviour, see https://roblox-ts.com/docs/api/roblox-api#exceptions
