### ISSUE TITLE
Instance.Clone method definition does not account for Instance.Archivable behavior

### ISSUE THREAD

**Issue by jheinem1** [roblox-ts/types#543]
According to the documentation of [Instance.Archivable](https://developer.roblox.com/en-us/api-reference/property/Instance/Archivable), when this property is `false`, it introduces the possibility of `Instance.Clone()` failing by returning `nil` rather than throwing an error.

> Calling Clone directly on an object will return nil if the cloned object is not archivable.

https://roblox-ts.com/playground/#code/DYUwLgBAlgdgzmAhjAxiCBeCMQHcICS8SqIAFAEQCyA9gCYjAUCUAdAMLA05nMQD0-CGAAWUOBBQ0ArsDoQARugAG0mAwBmsEHWUAoPQAcATrDBlYCZGlYA5RAFsQzIA

**Comment by Dionysusnu** [comment]
This is unfortunately a conscious decision that is slightly unsafe. The Archivable property is very rarely used, and the inconvenience of the possibly-undefined type outweighs the benefit of the better correctness.

**Comment by jheinem1** [comment]
Fair enough, though it may be necessary to add some sort of warning specifically when cloning models, as character models are not archivable by default.

**Comment by osyrisrblx** [comment]
I agree with what Dionysusnu said above. Going to close this for now.
