### ISSUE TITLE
BasePart:SubtractAsync (and potentially BasePart:UnionAsync) can return `nil` despite developer documentation

### ISSUE THREAD

**Issue by Agapurnis** [roblox-ts/types#570]
Relevant method documentation states that it will return an `Instance` (actually, an empty abstract extension of `PartOperation`, but that's irrelevant here)
 - https://developer.roblox.com/en-us/api-reference/function/BasePart/UnionAsync
 - https://developer.roblox.com/en-us/api-reference/function/BasePart/SubtractAsync
  
However, an official announcement and personal experience state that it can return `nil` in certain events.
> The operations throw an exception if there was a problem in computing the result (too many triangles, unsupported part types, the usual). **If the result is an empty mesh, they return `nil`**. If everything went well, they return a PartOperation representing the computed result, which can be used in subsequent operations if necessary.
>
> ~ [linearcomplex](https://devforum.roblox.com/u/linearcomplex), [New Roblox In-Game CSG API is now availabl](https://devforum.roblox.com/t/new-roblox-in-game-csg-api-is-now-available/174085), August 31, 2018

Emphasis (bold) mine.

This can be edited [here](https://github.com/roblox-ts/types/blob/c6b86efb16514b49fdc9b910f80fcbd22413ebe6/include/customDefinitions.d.ts#L91-L102), as overrides are already present.

**Comment by Dionysusnu** [comment]
This might be a case of #543, or might just be an oversight.

**Comment by Agapurnis** [comment]
> This might be a case of #543, or might just be an oversight.

I would be fine if it were solved similar to #543, as if it were forgotten in the documentation and an issue hasn't been raised here before, it obviously isn't a huge issue. This only really happened because I was negating things improperly, and this took me down the wrong direction.

**Comment by osyrisrblx** [comment]
Was able to reproduce this with `SubtractAsync`, but not `UnionAsync`. I thought if I negated one of the parts first and then unioned them together it would, but union async seems to treat negative parts as normal parts.
