### ISSUE TITLE
Fix CanvasGroup color

### ISSUE THREAD

**Issue by tacheometry** [roblox-ts/types#619]
The CanvasGroup instance has a `GroupColor3` property. Right now it's defined as `GroupColor`.

**Comment by Dionysusnu** [comment]
This actually was a rename in the last API dump update. It probably just still needs to run the weekly auto-generating update.

**Comment by Dionysusnu** [comment]
Or in fact it was even already updated 4 days ago: https://github.com/roblox-ts/types/commit/d910ba617e19d0f42b4ffa02b008d51af4a99375
Did you maybe forget to update your types package?

**Comment by tacheometry** [comment]
After running `npm i @rbxts/types@latest` it still gets me `Property 'GroupColor3' does not exist on type 'CanvasGroup'. Did you mean 'GroupColor'? ts(2551)`. It seems the latest version is 1.0.593, which doesn't have the type updated: https://unpkg.com/browse/@rbxts/types@1.0.593/include/generated/None.d.ts

**Comment by Dionysusnu** [comment]
1.0.598 has now been published and should include the change.
